quarkus.log.console.darken=0

quarkus.smallrye-health.root-path=health
test.whatever=whatever

%prod.quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.username=quarkus
%prod.quarkus.datasource.password=quarkus
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/quarkus
quarkus.hibernate-orm.schema-management.strategy = drop-and-create
